/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'geo-pages': GeoPage;
    testimonials: Testimonial;
    faqs: Faq;
    gallery: Gallery;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'geo-pages': GeoPagesSelect<false> | GeoPagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'business-settings': BusinessSetting;
  };
  globalsSelect: {
    'business-settings': BusinessSettingsSelect<false> | BusinessSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS admin accounts. Only admins can create new users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name in the admin panel
   */
  name: string;
  /**
   * Admin = full access. Editor = can edit content but not users or settings.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage images. Sharp auto-generates optimized sizes on upload.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text for accessibility and SEO (required)
   */
  alt: string;
  /**
   * Optional visible caption beneath the image
   */
  caption?: string | null;
  /**
   * Photo credit / attribution (optional)
   */
  credit?: string | null;
  /**
   * Tags for filtering in the media library
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Vehicle upfitting services offered to retail, fleet, dealer, and government clients.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Service name as displayed on the website
   */
  title: string;
  /**
   * Auto-generated from "title". Edit to override. Must be unique.
   */
  slug: string;
  /**
   * Full service description with rich text formatting
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Brief summary for cards, listings, and meta descriptions (max 300 chars)
   */
  shortDescription: string;
  /**
   * Audience segment this service targets
   */
  category: 'retail' | 'fleet' | 'dealer' | 'gov';
  /**
   * Primary image shown on service cards and hero sections
   */
  featuredImage?: (number | null) | Media;
  /**
   * Additional photos showcasing this service
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cities where this service is available — drives geo page associations
   */
  geoTags?:
    | {
        city: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Location-targeted landing pages for local SEO (e.g. "Vehicle Upfitting in Rockville MD").
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geo-pages".
 */
export interface GeoPage {
  id: number;
  /**
   * City name (e.g. "Rockville")
   */
  city: string;
  /**
   * Two-letter state code
   */
  state: string;
  /**
   * Auto-generated from "city". Edit to override. Must be unique.
   */
  slug: string;
  /**
   * Full page body — unique content per city for SEO
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Override headline (e.g. "Vehicle Upfitting in Rockville MD"). Auto-generated if blank.
   */
  heroHeadline?: string | null;
  /**
   * Services highlighted on this geo page
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Links to nearby location pages for internal linking
   */
  nearbyLocations?: (number | GeoPage)[] | null;
  /**
   * Flag indicating this page was auto-generated from a template
   */
  autoGenerate?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Customer reviews displayed on the website. Mark "Featured" to show on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Customer name (e.g. "Mike R.")
   */
  name: string;
  /**
   * Company or organization name (optional)
   */
  company?: string | null;
  /**
   * The full testimonial text (max 1000 chars)
   */
  review: string;
  /**
   * Star rating 1–5
   */
  rating: number;
  /**
   * Which service is this testimonial about?
   */
  service?: (number | null) | Service;
  /**
   * Show on homepage and featured sections
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Frequently asked questions, grouped by category. Used on service pages and the FAQ section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * The question as it will appear on the website
   */
  question: string;
  /**
   * Full answer — supports formatting, links, and lists
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Group for filtering on the frontend
   */
  category: 'general' | 'services' | 'pricing' | 'fleet' | 'warranty' | 'scheduling';
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Before/after project photos grouped by job. Powers the filterable gallery page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Project title (e.g. "2024 F-150 Patriot Liner + Tonneau")
   */
  title: string;
  /**
   * Project photos — tag before/after where applicable
   */
  images: {
    image: number | Media;
    /**
     * Optional description for this photo
     */
    caption?: string | null;
    /**
     * Tag for before/after comparisons
     */
    beforeAfter?: ('before' | 'after' | 'na') | null;
    id?: string | null;
  }[];
  /**
   * Link to the service performed
   */
  service?: (number | null) | Service;
  /**
   * Used for the frontend gallery filter tabs
   */
  category:
    | 'bedliner'
    | 'ceramic-coating'
    | 'hitches'
    | 'undercoating'
    | 'tonneau'
    | 'running-boards'
    | 'wraps'
    | 'fleet'
    | 'other';
  /**
   * Year / Make / Model of the vehicle in this project
   */
  vehicleInfo?: string | null;
  /**
   * Show in the homepage gallery section
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Inbound leads from the website contact/quote forms. Public can submit; only admins can view.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Full name of the person requesting a quote
   */
  name: string;
  /**
   * Contact email address
   */
  email: string;
  /**
   * Phone number (optional)
   */
  phone?: string | null;
  /**
   * Year / Make / Model of the vehicle
   */
  vehicle?: string | null;
  /**
   * Services the customer is interested in
   */
  requestedServices?:
    | {
        serviceName: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Free-form message from the customer
   */
  message?: string | null;
  /**
   * Audience segment
   */
  leadType?: ('retail' | 'fleet' | 'dealer-gov') | null;
  /**
   * Current pipeline stage
   */
  status?: ('new' | 'contacted' | 'quoted' | 'closed-won' | 'closed-lost') | null;
  /**
   * How the lead arrived
   */
  source?: ('web' | 'dealer' | 'referral' | 'phone' | 'walk-in') | null;
  /**
   * URL path the form was submitted from
   */
  sourcePage?: string | null;
  /**
   * Auto-generated reference ID (e.g. CU-XXXXXX)
   */
  refId?: string | null;
  /**
   * Submitter IP address (for abuse detection)
   */
  ipAddress?: string | null;
  /**
   * Internal notes about this lead (not shown to customer)
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'geo-pages';
        value: number | GeoPage;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  geoTags?:
    | T
    | {
        city?: T;
        id?: T;
      };
  sortOrder?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geo-pages_select".
 */
export interface GeoPagesSelect<T extends boolean = true> {
  city?: T;
  state?: T;
  slug?: T;
  content?: T;
  heroHeadline?: T;
  relatedServices?: T;
  nearbyLocations?: T;
  autoGenerate?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  review?: T;
  rating?: T;
  service?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        beforeAfter?: T;
        id?: T;
      };
  service?: T;
  category?: T;
  vehicleInfo?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  vehicle?: T;
  requestedServices?:
    | T
    | {
        serviceName?: T;
        id?: T;
      };
  message?: T;
  leadType?: T;
  status?: T;
  source?: T;
  sourcePage?: T;
  refId?: T;
  ipAddress?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Core business info — phone, email, address, service areas, SEO defaults, and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-settings".
 */
export interface BusinessSetting {
  id: number;
  /**
   * Legal business name displayed in the footer and schema markup
   */
  businessName: string;
  /**
   * Primary contact phone number
   */
  phone: string;
  /**
   * Primary contact email
   */
  email: string;
  /**
   * Business hours displayed on the site and in schema markup
   */
  hours?: string | null;
  /**
   * Used in the footer, contact page, and structured data
   */
  address: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  /**
   * Cities and regions served — shown in the footer and used by geo pages
   */
  serviceAreas?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Fallback meta tags when a page has no SEO overrides
   */
  defaultSeo?: {
    /**
     * Default <title> tag (max 70 chars)
     */
    metaTitle?: string | null;
    /**
     * Default meta description (max 160 chars)
     */
    metaDescription?: string | null;
    /**
     * Default Open Graph image (1200×630 recommended)
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Social profile URLs for the footer and structured data
   */
  socialLinks?: {
    google?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    yelp?: string | null;
  };
  /**
   * Promotional or urgency banner displayed across the top of every page
   */
  urgency?: {
    /**
     * Toggle the banner on/off globally
     */
    enabled?: boolean | null;
    /**
     * Primary banner text (e.g. "Spring Special — 15% Off Bedliners")
     */
    message1?: string | null;
    /**
     * Secondary rotating message (optional)
     */
    message2?: string | null;
  };
  /**
   * Link to the dealer partner portal
   */
  dealerPortalUrl?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-settings_select".
 */
export interface BusinessSettingsSelect<T extends boolean = true> {
  businessName?: T;
  phone?: T;
  email?: T;
  hours?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  serviceAreas?:
    | T
    | {
        area?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  socialLinks?:
    | T
    | {
        google?: T;
        facebook?: T;
        instagram?: T;
        youtube?: T;
        yelp?: T;
      };
  urgency?:
    | T
    | {
        enabled?: T;
        message1?: T;
        message2?: T;
      };
  dealerPortalUrl?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'geo-pages';
          value: number | GeoPage;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}