/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'geo-pages': GeoPage;
    testimonials: Testimonial;
    faqs: Faq;
    gallery: Gallery;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'geo-pages': GeoPagesSelect<false> | GeoPagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'business-settings': BusinessSetting;
  };
  globalsSelect: {
    'business-settings': BusinessSettingsSelect<false> | BusinessSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS admin accounts. Only admins can create new users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name in the admin panel
   */
  name: string;
  /**
   * Admin = full access. Editor = can edit content but not users or settings.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage images. Sharp auto-generates optimized sizes on upload.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text for accessibility and SEO (required)
   */
  alt: string;
  /**
   * Optional visible caption beneath the image
   */
  caption?: string | null;
  /**
   * Photo credit / attribution (optional)
   */
  credit?: string | null;
  /**
   * Tags for filtering in the media library
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Vehicle upfitting services shown on the site. Each service maps to a /services/[slug] page. Publish to make it live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Service name as shown on the site. E.g. "Spray-On Bedliners (Patriot Liner)"
   */
  title: string;
  /**
   * One sentence used in service cards and meta descriptions. 150–300 chars. E.g. "Factory-certified Patriot Liner spray-on bedliners — lifetime warranty included."
   */
  shortDescription: string;
  /**
   * Full page body content. Use H2/H3 headings, bullet lists, and clear benefit-driven copy. This renders on the /services/[slug] page via the Lexical renderer.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Who this service is for. Retail = truck owners, Fleet = businesses with multiple vehicles.
   */
  category: 'retail' | 'fleet' | 'dealer' | 'gov';
  /**
   * Order in which this service appears in the grid. Lower numbers appear first. Bedliner = 1, Hitches = 2, etc.
   */
  sortOrder?: number | null;
  /**
   * Hero image for this service. Used as the card image on the services grid and the page hero background. Recommended: 1920×1080 JPG, under 500KB. Use the Image Generator prompts (see admin dashboard) to create scroll-stopping visuals.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Before/after photos or completed project images. These show in the gallery section on the service page.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Optional caption. E.g. "2024 Ford F-150 — full Patriot Liner with UV topcoat"
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cities this service targets for local SEO. Used to build /services/[service]/[city] geo pages automatically.
   */
  geoTags?:
    | {
        /**
         * E.g. "Rockville", "Bethesda", "Silver Spring"
         */
        city: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL-safe identifier. Auto-generated from title. E.g. "bedliner". This becomes /services/bedliner. DO NOT change after publishing — it will break links.
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Location-specific landing pages for local SEO. Each page targets search queries like "vehicle upfitting near [City], MD". Publishes to /locations/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geo-pages".
 */
export interface GeoPage {
  id: number;
  /**
   * City name. E.g. "Bethesda" or "Silver Spring".
   */
  city: string;
  /**
   * Two-letter state code. E.g. "MD", "VA", "DC".
   */
  state: string;
  /**
   * H1 headline for this geo page. E.g. "Vehicle Upfitting in Bethesda, MD". Auto-uses city name if blank.
   */
  heroHeadline?: string | null;
  /**
   * Main page body. Write 300–600 words of locally-relevant copy. Mention nearby neighborhoods, landmarks, and how far the city is from the Rockville shop. Include 2–3 service mentions with internal links.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Services shown in the "Available Near [City]" grid. Select all services unless a specific city is only served by some. Affects the /locations/[slug] page grid.
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Other geo pages shown as "Also Serving" links at the bottom. Builds internal link equity between location pages.
   */
  nearbyLocations?: (number | GeoPage)[] | null;
  /**
   * URL-safe ID. Auto-generated as "[city]-[state]". E.g. "bethesda-md". Becomes /locations/bethesda-md. DO NOT change after publishing.
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Customer reviews displayed on the homepage and service pages. Set "Featured" to show on the homepage. Link to a service to show on that service's page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Customer first name + last initial. E.g. "Mike R."
   */
  name: string;
  /**
   * Optional company name. E.g. "Rockville Landscaping LLC". Leave blank for personal vehicles.
   */
  company?: string | null;
  /**
   * The review text. 1–4 sentences. Keep it authentic — avoid making edits that sound promotional.
   */
  review: string;
  /**
   * Star rating from the customer.
   */
  rating: '5' | '4' | '3';
  /**
   * Show on homepage?
   */
  featured?: boolean | null;
  /**
   * Which service this review is about. Linking a testimonial to a service makes it appear on that service's page.
   */
  service?: (number | null) | Service;
  /**
   * Where this review came from. Google reviews have the highest trust signal.
   */
  source?: ('google' | 'yelp' | 'facebook' | 'direct') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Frequently asked questions. These appear as an FAQ accordion on service and contact pages. Each FAQ generates a FAQPage schema entry for Google rich results.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * The question as a customer would ask it. Start with "How", "What", "Do you", "Can I", etc. This shows as the accordion header.
   */
  question: string;
  /**
   * The full answer. 2–4 sentences. Can include links to relevant service pages. This generates a FAQPage schema entry that may appear in Google's featured snippets.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Category determines which pages this FAQ appears on. "General" shows on the contact and homepage. Service-specific categories filter to their respective pages.
   */
  category: 'general' | 'services' | 'fleet' | 'scheduling' | 'warranty' | 'pricing';
  /**
   * Display order within its category. Lower = shown first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Before/after project photos grouped by job. Powers the filterable gallery page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Project title (e.g. "2024 F-150 Patriot Liner + Tonneau")
   */
  title: string;
  /**
   * Project photos — tag before/after where applicable
   */
  images: {
    image: number | Media;
    /**
     * Optional description for this photo
     */
    caption?: string | null;
    /**
     * Tag for before/after comparisons
     */
    beforeAfter?: ('before' | 'after' | 'na') | null;
    id?: string | null;
  }[];
  /**
   * Link to the service performed
   */
  service?: (number | null) | Service;
  /**
   * Used for the frontend gallery filter tabs
   */
  category:
    | 'bedliner'
    | 'ceramic-coating'
    | 'hitches'
    | 'undercoating'
    | 'tonneau'
    | 'running-boards'
    | 'wraps'
    | 'fleet'
    | 'other';
  /**
   * Year / Make / Model of the vehicle in this project
   */
  vehicleInfo?: string | null;
  /**
   * Show in the homepage gallery section
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Inbound quote requests and contact form submissions from the website. NEW leads require follow-up. Update status as you work through them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone?: string | null;
  email?: string | null;
  /**
   * Year, make, model. E.g. "2023 Ford F-150 SuperCrew"
   */
  vehicle?: string | null;
  /**
   * Customer's message or notes from the form.
   */
  message?: string | null;
  /**
   * Type of customer.
   */
  leadType: 'retail' | 'fleet' | 'dealer-gov' | 'contact' | 'quote';
  /**
   * Follow-up status. Update this as you work the lead.
   */
  status: 'new' | 'in-progress' | 'quoted' | 'won' | 'lost' | 'spam';
  /**
   * Services the customer asked about. Populated from the quote form checkboxes.
   */
  requestedServices?:
    | {
        serviceName: string;
        id?: string | null;
      }[]
    | null;
  source?: ('web' | 'dealer' | 'referral' | 'phone' | 'walk-in') | null;
  /**
   * URL path where form was submitted. E.g. /services/bedliner
   */
  sourcePage?: string | null;
  /**
   * Auto-captured for spam detection.
   */
  ipAddress?: string | null;
  /**
   * Auto-generated unique ID sent to the customer in confirmation email.
   */
  refId?: string | null;
  /**
   * Should always be empty. Non-empty = bot submission.
   */
  honeypot?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'geo-pages';
        value: number | GeoPage;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  category?: T;
  sortOrder?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  geoTags?:
    | T
    | {
        city?: T;
        id?: T;
      };
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geo-pages_select".
 */
export interface GeoPagesSelect<T extends boolean = true> {
  city?: T;
  state?: T;
  heroHeadline?: T;
  content?: T;
  relatedServices?: T;
  nearbyLocations?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  review?: T;
  rating?: T;
  featured?: T;
  service?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        beforeAfter?: T;
        id?: T;
      };
  service?: T;
  category?: T;
  vehicleInfo?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  vehicle?: T;
  message?: T;
  leadType?: T;
  status?: T;
  requestedServices?:
    | T
    | {
        serviceName?: T;
        id?: T;
      };
  source?: T;
  sourcePage?: T;
  ipAddress?: T;
  refId?: T;
  honeypot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Core business info — phone, email, address, service areas, SEO defaults, and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-settings".
 */
export interface BusinessSetting {
  id: number;
  /**
   * Legal business name displayed in the footer and schema markup
   */
  businessName: string;
  /**
   * Primary contact phone number
   */
  phone: string;
  /**
   * Primary contact email
   */
  email: string;
  /**
   * Business hours displayed on the site and in schema markup
   */
  hours?: string | null;
  /**
   * Used in the footer, contact page, and structured data
   */
  address: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  /**
   * Cities and regions served — shown in the footer and used by geo pages
   */
  serviceAreas?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Fallback meta tags when a page has no SEO overrides
   */
  defaultSeo?: {
    /**
     * Default <title> tag (max 70 chars)
     */
    metaTitle?: string | null;
    /**
     * Default meta description (max 160 chars)
     */
    metaDescription?: string | null;
    /**
     * Default Open Graph image (1200×630 recommended)
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Social profile URLs for the footer and structured data
   */
  socialLinks?: {
    google?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    yelp?: string | null;
  };
  /**
   * Promotional or urgency banner displayed across the top of every page
   */
  urgency?: {
    /**
     * Toggle the banner on/off globally
     */
    enabled?: boolean | null;
    /**
     * Primary banner text (e.g. "Spring Special — 15% Off Bedliners")
     */
    message1?: string | null;
    /**
     * Secondary rotating message (optional)
     */
    message2?: string | null;
  };
  /**
   * Link to the dealer partner portal
   */
  dealerPortalUrl?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-settings_select".
 */
export interface BusinessSettingsSelect<T extends boolean = true> {
  businessName?: T;
  phone?: T;
  email?: T;
  hours?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  serviceAreas?:
    | T
    | {
        area?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  socialLinks?:
    | T
    | {
        google?: T;
        facebook?: T;
        instagram?: T;
        youtube?: T;
        yelp?: T;
      };
  urgency?:
    | T
    | {
        enabled?: T;
        message1?: T;
        message2?: T;
      };
  dealerPortalUrl?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}